// <auto-generated />
namespace E_CommerceAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addProductandCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addProductandCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202007191900201_add Product and Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
